# Generated by Django 2.1.7 on 2019-03-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/inventory/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(max_length=15, verbose_name='ASIN')),
                ('upc', models.CharField(max_length=15, verbose_name='UPC')),
                ('ein', models.CharField(max_length=15, verbose_name='EIN')),
                ('sku', models.CharField(max_length=15, verbose_name='SKU')),
                ('wholesale_units', models.IntegerField(default=0)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='ROI')),
                ('buy_box', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('buy_box_avg90', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Buy Box - 90 Days AVG')),
                ('buy_box_min', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('buy_box_max', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('buy_box_min_date', models.DateField()),
                ('buy_box_max_date', models.DateField()),
                ('review_count', models.IntegerField(default=0, verbose_name='Reviews')),
                ('review_count_last30', models.IntegerField(default=0, verbose_name='Reviews - Last 30 Days')),
                ('review_count_avg90', models.IntegerField(default=0, verbose_name='Reviews - 90 Days AVG')),
                ('sales_rank', models.IntegerField(default=0)),
                ('sales_rank_avg90', models.IntegerField(default=0, verbose_name='Sales Rank - 90 Days AVG')),
                ('fba_sellers_count', models.IntegerField(default=0)),
                ('root_category', models.CharField(max_length=255)),
                ('sales_estimate', models.IntegerField(default=0)),
                ('three_month_supply_cost', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('three_month_supply_amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Discarded'), (2, 'Highlighted'), (3, 'Approved')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Supplier'),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='products',
            field=models.ManyToManyField(related_name='files', to='products.Product'),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='products.Supplier'),
        ),
    ]
