# Generated by Django 2.1.7 on 2019-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupload',
            name='identifier_col',
            field=models.CharField(default='UPC', max_length=255, verbose_name='Identifier Column'),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='identifier_type',
            field=models.IntegerField(choices=[(0, 'ASIN'), (1, 'UPC'), (2, 'EIN')], default=1),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='price_col',
            field=models.CharField(default='Price', max_length=255, verbose_name='Price Column'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box_avg90',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Buy Box - 90 Days AVG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box_max_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_box_min_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ein',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='EIN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fba_sellers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count_avg90',
            field=models.IntegerField(blank=True, default=0, verbose_name='Reviews - 90 Days AVG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_count_last30',
            field=models.IntegerField(blank=True, default=0, verbose_name='Reviews - Last 30 Days'),
        ),
        migrations.AlterField(
            model_name='product',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='ROI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='root_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_estimate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_rank_avg90',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sales Rank - 90 Days AVG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='three_month_supply_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='three_month_supply_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_units',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
