# Generated by Django 2.1.7 on 2019-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190303_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_by_amazon',
            field=models.BooleanField(default=False),
        ),
    ]
