# Generated by Django 2.1.7 on 2019-03-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190303_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupload',
            name='analysed_products',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='email_on_completion',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='failed_analysis_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='failed_products',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='processed_products',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='status',
            field=models.IntegerField(choices=[(0, 'Analysis Pending'), (1, 'Analysis in Process'), (2, 'Analysis Finished'), (3, 'Analysis Finished With Some Failures'), (4, 'Analysis Failed')], default=0),
        ),
        migrations.AddField(
            model_name='inventoryupload',
            name='total_products',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='failed_analysis_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending Analysis'), (1, 'Thumbs Down :('), (2, 'Highlighted'), (3, 'Thumbs Up :)'), (4, 'Analysis Failed')], default=0),
        ),
    ]
