# Generated by Django 2.1.7 on 2019-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190303_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
    ]
