# Generated by Django 2.1.7 on 2019-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('max_rank', models.IntegerField(default=500000)),
            ],
        ),
    ]
