# Generated by Django 2.1.7 on 2019-03-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_amazoncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategoryId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AmazonCategorySalesRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_allowed', models.IntegerField(default=500000)),
                ('preferred', models.IntegerField(default=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='AmazonCategory',
        ),
        migrations.AddField(
            model_name='amazoncategoryid',
            name='sales_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_ids', to='products.AmazonCategorySalesRank'),
        ),
    ]
