# Generated by Django 2.1.7 on 2019-03-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190305_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('category_id', models.IntegerField()),
                ('products_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='amazoncategoryid',
            name='sales_rank',
        ),
        migrations.AlterField(
            model_name='amazoncategorysalesrank',
            name='max_allowed',
            field=models.IntegerField(default=200000),
        ),
        migrations.AlterField(
            model_name='amazoncategorysalesrank',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='AmazonCategoryId',
        ),
        migrations.AddField(
            model_name='amazoncategory',
            name='sales_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_ids', to='products.AmazonCategorySalesRank'),
        ),
    ]
