# Generated by Django 2.1.7 on 2019-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190306_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoncategory',
            name='highest_rank',
            field=models.IntegerField(default=0),
        ),
    ]
