# Generated by Django 2.1.7 on 2019-03-08 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190306_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(max_length=15, verbose_name='ASIN')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('profit_median', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('profit_avg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='ROI')),
                ('buy_box', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_median', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_std_dev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_variance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_avg90', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Buy Box - 90 Days AVG')),
                ('buy_box_min', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_max', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('buy_box_min_date', models.DateField(blank=True, null=True)),
                ('buy_box_max_date', models.DateField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, default=0, verbose_name='Reviews')),
                ('review_count_last30', models.IntegerField(blank=True, default=0, verbose_name='Reviews - Last 30 Days')),
                ('review_count_avg90', models.IntegerField(blank=True, default=0, verbose_name='Reviews - 90 Days AVG')),
                ('sales_rank', models.IntegerField(blank=True, default=0)),
                ('sales_rank_median', models.IntegerField(blank=True, default=0)),
                ('sales_rank_avg90', models.IntegerField(blank=True, default=0, verbose_name='Sales Rank - 90 Days AVG')),
                ('sales_rank_std_dev', models.IntegerField(blank=True, default=0)),
                ('sales_rank_std_variance', models.IntegerField(blank=True, default=0)),
                ('fba_sellers_count', models.IntegerField(blank=True, default=0)),
                ('root_category', models.CharField(blank=True, default='', max_length=255)),
                ('sales_estimate_current', models.IntegerField(blank=True, default=0)),
                ('sales_estimate_avg', models.IntegerField(blank=True, default=0)),
                ('three_month_supply_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11)),
                ('three_month_supply_amount', models.IntegerField(blank=True, default=0)),
                ('sold_by_amazon', models.BooleanField(default=False)),
                ('isAddOn', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='asin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box_avg90',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box_max_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_box_min_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fba_sellers_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count_avg90',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count_last30',
        ),
        migrations.RemoveField(
            model_name='product',
            name='roi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='root_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_estimate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_rank',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_rank_avg90',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_by_amazon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='three_month_supply_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='three_month_supply_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_units',
        ),
        migrations.AddField(
            model_name='product',
            name='set_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='amazonproductlisting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_listings', to='products.Product'),
        ),
    ]
