# Generated by Django 2.1.7 on 2019-03-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190307_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproductlisting',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='products.AmazonCategory'),
        ),
    ]
