# Generated by Django 2.1.7 on 2019-03-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190308_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductlisting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Thumbs Down :('), (1, 'Highlighted'), (2, 'Recommended'), (3, 'Thumbs Up :)')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending Analysis'), (1, 'Analysis Successful'), (2, 'Analysis Failed')], default=0),
        ),
    ]
