# Generated by Django 2.1.7 on 2019-03-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190308_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductlisting',
            name='rating_current',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
